# Generated by Django 5.0.6 on 2024-12-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_order_customer_remove_order_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
